export * from './types.js';
export * from './SFCParser.js';
export * from './SFCCompiler.js';
export * from './VueResolver.js';
export * from './HMR.js';
export * from './hmr/descriptorCache.js';
export * from './hmr/statePreserver.js';
export * from './hmr/boundary.js';
export * from './hmr/updateHandler.js';
export * from './hmr/accept.js';
export { vuePlugin, vuePlugin as default } from './VuePlugin.js';
